version: "3.3"
services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=pokemon
      - MYSQL_ROOT_PASSWORD=nodepassword
      - MYSQL_HOST=db
      - MYSQL_USER=doggo
      - MYSQL_PASSWORD=doggo123
    expose:
      - "3306"
    volumes:
      - db:/var/lib/mysql

  api:
    build: .
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - "80:8080"
    depends_on:
      - db
    environment:
      - MYSQL_DATABASE=pokemon
      - MYSQL_ROOT_PASSWORD=nodepassword
      - MYSQL_HOST=db
      - MYSQL_USER=doggo
      - MYSQL_PASSWORD=doggo123
    stdin_open:  true
    tty: true
volumes:
  db:
